pre-commit:
  parallel: true
  commands:
    lint:
      run: pnpm run lint:fix
    typecheck:
      run: pnpm run typecheck

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}